name: Build APK (Boss Mode)

on:
  workflow_dispatch:  # Kézi indítás a GitHub Actions felületen

jobs:
  build:
    name: Build Manager APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build Debug APK
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew assembleRelease -PsignAsDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: revanced-manager-bossmode
          path: app/build/outputs/apk/release/revanced-manager*.apk
          archive: false
